name: CI Apps workflow

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths-ignore:
      - "AoC/**"
      - "AoC.Tests/**"

env:
  AocPuzzleInputCryptoKey: ${{ secrets.AOC_PUZZLE_INPUT_CRYPTO_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build Apps
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Debug --no-restore # Note `Debug` to verify everything compiles, but avoid expensive linking operations performed by `Release` builds
