name: App releases

on:
  push:
    branches:
      - main

env:
  AocPuzzleInputCryptoKey: ${{ secrets.AOC_PUZZLE_INPUT_CRYPTO_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Publish and release
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100
    - name: Publish Linux CLI
      run: dotnet publish AoC.CLI -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true
    - name: Publish Windows CLI
      run: dotnet publish AoC.CLI -c Release -r win-x64 --self-contained -p:PublishSingleFile=true
    - name: Get most recent day name
      id: vars
      run: echo "MostRecentDayTitle=$(dotnet run --project AoC.CLI --most-recent-day-title)" >> $GITHUB_OUTPUT
    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Create GitHub release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ github.run_number }}"
        prerelease: false
        title: "v${{ github.run_number }} (${{ steps.vars.outputs.MostRecentDayTitle }})"
        files: |
          AoC.CLI/bin/Release/net8.0/linux-x64/publish/AoC.CLI
          AoC.CLI/bin/Release/net8.0/win-x64/publish/AoC.CLI.exe
